### ISSUE TITLE
Logout bug ((feature-chat))

### ISSUE THREAD

**Issue by SgtCroWbaR** [MATF-Computer-Networks-Projects/2021_DestinedSouls#8]
1) Client\src\app\components\homepage\homepage.component.ts : 19
HomepageComponent.onLogout() : doesn't route to '/login' anymore;

2) Client\src\app\services\authentication.service.ts : 34
AuthenticationService.logout() : need a solution that returns http.delete and then unloads AuthenticationService.currentUserSubject

**Comment by SgtCroWbaR** [comment]
Everything works fine if you 'just' reload homepage after clicking on Logout button

**Comment by djordjetane** [comment]
#9 Check fix and merge if applicable. This is a temp fix to allow further design capabilty.
